name: Wordpress Automation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  job1:
    
    name: Build
    runs-on: ubuntu-latest
    steps:
              
      - name: deployer
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.CLIENT_APPS_HOST }}
          username: ${{ secrets.CLIENT_APPS_USERNAME }}
          password: ${{ secrets.CLIENT_APPS_PASSWORD }}
          server-dir: /home/cltappswebop/public_html/demo/

