name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  web-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deployer
        uses: isthatcentered/dist-to-ftp@v1
        with:
          host: 164.52.195.177
          port: 21
          user: cltappswebop
          password: 68V&!8leE8Ac
          into: ./public_html/demo/
          path: ./
