name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  job1:
    
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Content list

        uses: enricomarino/actions@v2
        with:
          source: /
