name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  job-one:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deployer
        uses: GenieTim/ftp-action@v4.0.1
        with:
          host: 164.52.195.177
          user: cltappswebop
          password: 68V&!8leE8Ac
          remoteDir: ./public_html/demo
