name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  web-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deployer
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 164.52.195.177
          username: cltappswebop
          password: 68V&!8leE8Ac
          server-dir: ./public_html/demo/
