name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  job1:
    
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: git-ftp push
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: 164.52.195.177
          ftp_username: cltappswebop
          ftp_password: 68V&!8leE8Ac
          local_source_dir: "wp-admin"
          dist_target_dir: "public_html/demo"

